# chrome_binary_path: "/usr/bin/google-chrome"  # Path to Chrome binary
# user_data_dir: "~/chrome-data"                # Directory to store Chrome profile
debug_port: 9222                                # Port to connect over devtools protocol
